export const seriesList = [
  {
    title: "Breaking Bad",
    seasons: 5,
    episodes: 62,
    genre: "Crime, Drama, Thriller",
    thumbnail: "/shows/breaking-bad-thub.jpg",
    platform: "Netflix",
    slug: "breaking-bad",
    platformSlug: "netflix",
    description:
      "Příběh chemikáře Waltera Whitea, který se stává výrobcem drog, aby zajistil rodinu. Seriál sleduje jeho proměnu z učitele na obávaného drogového magnáta.",
    banner: "/shows/breaking-bad-banner.webp",
    logo: "/shows/breaking-bad-logo.png",
  },
  {
    title: "Game of Thrones",
    seasons: 8,
    episodes: 73,
    genre: "Action, Adventure, Drama",
    thumbnail:
      "https://upload.wikimedia.org/wikipedia/en/d/d8/Game_of_Thrones_title_card.jpg",
    platform: "Max",
    slug: "game-of-thrones",
    platformSlug: "max",
    description:
      "Boj o trůn v fiktivním světě plném intrik a magie. Seriál je známý svými nečekanými zvraty a komplikovanými postavami.",
    banner: "/shows/game-of-thrones-banner.jpg",
    logo: "/shows/game-of-thrones-logo.png",
  },
  {
    title: "Stranger Things",
    seasons: 4,
    episodes: 34,
    genre: "Drama, Fantasy, Horror",
    thumbnail: "/shows/stranger-things-thub.jpg",
    platform: "Netflix",
    platformSlug: "netflix",
    slug: "stranger-things",
    banner: "/shows/stranger-things-banner.jpg",
    logo: "/shows/stranger-things-logo.png",
    description:
      "Skupina dětí se snaží najít svého ztraceného přítele a objevují tajemný svět plný nebezpečí. Seriál kombinuje nostalgii 80. let s nadpřirozenými prvky.",
  },
  {
    title: "The Mandalorian",
    seasons: 2,
    episodes: 16,
    genre: "Action, Adventure, Fantasy",
    thumbnail: "/shows/mandalorian-thub.webp",
    platform: "Disney+",
    platformSlug: "disney-plus",
    slug: "the-mandalorian",
    banner: "/shows/the-mandalorian-banner.jpg",
    logo: "/shows/mandalorian-logo.png",
    description:
      "Příběh osamělého lovce odměn ve světě Star Wars. Seriál sleduje jeho dobrodružství a snahu ochránit malé dítě s mocnými schopnostmi.",
  },
  {
    title: "The Crown",
    seasons: 5,
    episodes: 50,
    genre: "Biography, Drama, History",
    thumbnail: "/shows/crown-thub.jpg",
    platform: "Netflix",
    platformSlug: "netflix",
    slug: "the-crown",
    banner: "/shows/the-crown-banner.jpg",
    logo: "/shows/the-crown-logo.png",
    description:
      "Historický seriál sledující vládu královny Alžběty II. Ukazuje důležité události a osobní život členů britské královské rodiny.",
  },
  {
    title: "Friends",
    seasons: 10,
    episodes: 236,
    genre: "Comedy, Romance",
    thumbnail: "/shows/friends-thub.jpg",
    platform: "Max",
    platformSlug: "max",
    slug: "friends",
    banner: "/shows/friends-banner.jpg",
    logo: "/shows/friends-logo.png",
    description:
      "Komediální seriál o skupině přátel žijících v New Yorku. Sleduje jejich každodenní život, romantické vztahy a vtipné situace.",
  },
  {
    title: "Westworld",
    seasons: 4,
    episodes: 36,
    genre: "Drama, Mystery, Sci-Fi",
    thumbnail: "/shows/westworld-thub.webp",
    platform: "Max",
    platformSlug: "max",
    slug: "westworld",
    banner: "/shows/westworld-banner.jpg",
    logo: "/shows/westworld-logo.png",
    description:
      "Sci-fi seriál odehrávající se v futuristickém zábavním parku obydleném androidy. Sleduje vzpouru robotů proti svým lidským tvůrcům.",
  },
  {
    title: "The Witcher",
    seasons: 3,
    episodes: 24,
    genre: "Action, Adventure, Drama",
    thumbnail: "/shows/witcher-thub.webp",
    platform: "Netflix",
    platformSlug: "netflix",
    slug: "the-witcher",
    banner: "/shows/the-witcher-banner.jpeg",
    logo: "/shows/the-witcher-logo.png",
    description:
      "Dobrodružství Geralta z Rivie, osamělého lovce příšer ve světě plném magie a nebezpečí. Seriál je adaptací populární knižní série.",
  },
  {
    title: "Dark",
    seasons: 3,
    episodes: 26,
    genre: "Crime, Drama, Mystery",
    thumbnail: "/shows/dark-thub.png",
    platform: "Netflix",
    platformSlug: "netflix",
    banner: "/shows/dark-banner.jpg",
    logo: "/shows/dark-logo.png",
    slug: "dark",
    description:
      "Německý sci-fi thriller, který se točí kolem zmizení dětí a časových paradoxů. Seriál zkoumá, jak minulost, přítomnost a budoucnost jsou propojené.",
  },
  {
    title: "Black Mirror",
    seasons: 5,
    episodes: 22,
    genre: "Drama, Sci-Fi, Thriller",
    thumbnail: "/shows/black-mirror-thub.jpg",
    platform: "Netflix",
    platformSlug: "netflix",
    slug: "black-mirror",
    banner: "/shows/black-mirror-banner.jpg",
    logo: "/shows/black-mirror-logo.png",
    description:
      "Antologický seriál zkoumající temnou stránku moderní technologie a její vliv na společnost. Každá epizoda představuje samostatný příběh s dystopickým nádechem.",
  },
  {
    title: "Fargo",
    seasons: 4,
    episodes: 41,
    genre: "Crime, Drama, Thriller",
    thumbnail: "/shows/fargo-thub.jpg",
    platform: "Max",
    platformSlug: "max",
    banner: "/shows/fargo-banner.jpg",
    logo: "/shows/fargo-logo.svg",
    slug: "fargo",
    description:
      "Kriminální drama inspirované stejnojmenným filmem. Každá sezóna představuje nový příběh plný zločinů a nečekaných zvratů.",
  },
  {
    title: "Mindhunter",
    seasons: 2,
    episodes: 19,
    genre: "Crime, Drama, Thriller",
    thumbnail: "/shows/mindhunter-thub.jpg",
    platform: "Netflix",
    platformSlug: "netflix",
    banner: "/shows/mindhunter-banner.jpg",
    logo: "/shows/mindhunter-logo.svg",
    slug: "mindhunter",
    description:
      "Seriál sleduje počátky profilování sériových vrahů u FBI. Hlavní postavy rozhovory s vrahy, aby pochopily jejich psychologii.",
  },
  {
    title: "The Boys",
    seasons: 3,
    episodes: 24,
    genre: "Action, Comedy, Crime",
    thumbnail: "/shows/the_boys-thub.jpg",
    platform: "Amazon Prime Video",
    platformSlug: "amazon-prime-video",
    banner: "/shows/the-boys-banner.jpg",
    logo: "/shows/the-boys-logo.png",
    slug: "the-boys",
    description:
      "Akční satira o skupině vigilantes bojující proti zkorumpovaným superhrdinům. Seriál zkoumá temnou stránku superhrdinského žánru.",
  },
  {
    title: "Better Call Saul",
    seasons: 6,
    episodes: 63,
    genre: "Crime, Drama",
    thumbnail: "/shows/call-saul-thub.jpg",
    platform: "Netflix",
    platformSlug: "netflix",
    slug: "better-call-saul",
    banner: "/shows/better-call-saul-saul-banner.jpg",
    logo: "/shows/better-call-saul-saul-logo.png",
    description:
      "Prequel k seriálu Breaking Bad, sledující cestu Jima McGilla k jeho alter egu Saul Goodman. Seriál nabízí hlubší pohled na jeho právnickou kariéru.",
  },
  {
    title: "Chernobyl",
    seasons: 1,
    episodes: 5,
    genre: "Drama, History, Thriller",
    thumbnail: "/shows/chernobyl-thub.jpg",
    platform: "Max",
    platformSlug: "max",
    slug: "chernobyl",
    banner: "/shows/chernobyl-banner.jpeg",
    logo: "/shows/chernobyl-logo.svg",
    description:
      "Dramatizace jedné z nejhorších jaderných katastrof v historii. Seriál sleduje události před a po výbuchu v Černobylu.",
  },
  {
    title: "The Expanse",
    seasons: 6,
    episodes: 62,
    genre: "Drama, Mystery, Sci-Fi",
    thumbnail: "/shows/the-expanse-thub.avif",
    platform: "Amazon Prime Video",
    platformSlug: "amazon-prime-video",
    banner: "/shows/the-expanse-banner.jpg",
    logo: "/shows/the-expanse-logo.png",
    slug: "the-expanse",
    description:
      "Sci-fi seriál odehrávající se ve vzdálené budoucnosti, kdy lidstvo kolonizovalo sluneční soustavu. Seriál sleduje politické intriky a konflikty mezi Zemí, Marsem a Asteroidovým pásem.",
  },
  {
    title: "The Handmaid's Tale",
    seasons: 5,
    episodes: 56,
    genre: "Drama, Sci-Fi, Thriller",
    thumbnail: "/shows/the-handmaids-tale-thub.jpg",
    platform: "Hulu",
    platformSlug: "hulu",
    slug: "the-handmaids-tale",
    banner: "/shows/the-handmaids-tale-banner.jpeg",
    logo: "/shows/the-handmaids-tale-logo.svg",
    description:
      "Dystopický příběh o totalitním režimu, kde ženy jsou nuceny k reprodukci. Seriál sleduje boj jedné ženy za svobodu.",
  },
  {
    title: "Peaky Blinders",
    seasons: 6,
    episodes: 36,
    genre: "Crime, Drama",
    thumbnail: "/shows/peaky-blinders-thub.jpg",
    platform: "Netflix",
    platformSlug: "netflix",
    slug: "peaky-blinders",
    banner: "/shows/peaky-blinders-banner.jpg",
    logo: "/shows/peaky-blinders-logo.png",
    description:
      "Kriminální drama odehrávající se v Británii po první světové válce. Seriál sleduje gang vedený charismatickým Thomasem Shelbyem.",
  },
  {
    title: "Narcos",
    seasons: 3,
    episodes: 30,
    genre: "Biography, Crime, Drama",
    thumbnail: "/shows/narcos-thub.jpg",
    platform: "Netflix",
    platformSlug: "netflix",
    slug: "narcos",
    banner: "/shows/narcos-banner.jpg",
    logo: "/shows/narcos-logo.png",
    description:
      "Seriál sleduje vzestup a pád drogového krále Pabla Escobara. Zobrazuje boj kolumbijských a amerických agentů proti drogovým kartelům.",
  },
  {
    title: "The Umbrella Academy",
    seasons: 3,
    episodes: 30,
    genre: "Action, Adventure, Comedy",
    thumbnail: "/shows/umbrella-academy-thub.jpg",
    platform: "Netflix",
    platformSlug: "netflix",
    slug: "the-umbrella-academy",
    banner: "/shows/the-umbrella-academy-banner.jpg",
    logo: "/shows/the-umbrella-academy-logo.png",
    description:
      "Příběh adoptivní rodiny superhrdinů, kteří se musí spojit, aby zachránili svět. Seriál kombinuje akci, humor a rodinné drama.",
  },
  {
    title: "Rick and Morty",
    seasons: 6,
    episodes: 61,
    genre: "Animation, Adventure, Comedy",
    thumbnail: "/shows/rick-and-morty-thub.jpg",
    platform: "Max",
    platformSlug: "max",
    slug: "rick-and-morty",
    banner: "/shows/rick-and-morty-banner.jpg",
    logo: "/shows/rick-and-morty-logo.svg",
    description:
      "Animovaný seriál sledující dobrodružství šíleného vědce Ricka a jeho vnuka Mortyho. Seriál je plný černého humoru a sci-fi prvků.",
  },
  {
    title: "Ozark",
    seasons: 4,
    episodes: 44,
    genre: "Crime, Drama, Thriller",
    thumbnail: "/shows/ozark-thub.webp",
    banner: "/shows/ozark-banner.jpeg",
    logo: "/shows/ozark-logo.svg",
    platform: "Netflix",
    platformSlug: "netflix",
    slug: "ozark",
    description:
      "Finanční poradce se přestěhuje s rodinou do Ozarks, aby pral peníze pro drogový kartel. Seriál sleduje jeho boj o přežití a udržení rodiny v bezpečí.",
  },
  {
    title: "Succession",
    seasons: 4,
    episodes: 39,
    genre: "Drama",
    thumbnail: "/shows/succession-thub.webp",
    platform: "Max",
    platformSlug: "max",
    banner: "/shows/succession-banner.jpg",
    logo: "/shows/succession-logo.png",
    slug: "succession",
    description:
      "Drama o bohaté rodině bojující o kontrolu nad mediálním impériem. Seriál zkoumá intriky a mocenské boje mezi členy rodiny.",
  },
  {
    title: "Money Heist",
    seasons: 5,
    episodes: 41,
    genre: "Action, Crime, Drama",
    thumbnail: "/shows/money-heist-thub.jpg",
    platform: "Netflix",
    platformSlug: "netflix",
    banner: "/shows/money-heist-banner.jpg",
    logo: "/shows/money-heist-logo.png",
    slug: "money-heist",
    description:
      "Skupina zločinců plánuje a provádí největší loupež v historii Španělska. Seriál sleduje jejich taktiky a osobní konflikty.",
  },
  {
    title: "The Office",
    seasons: 9,
    episodes: 201,
    genre: "Comedy",
    banner: "/shows/the-office-banner.jpg",
    logo: "/shows/the-office-logo.svg",
    thumbnail: "/shows/the-office-thub.webp",
    platform: "Peacock",
    platformSlug: "peacock",
    slug: "the-office",
    description:
      "Kultovní komediální seriál odehrávající se v kanceláři firmy Dunder Mifflin. Sleduje každodenní život a bláznivé situace zaměstnanců.",
  },
  {
    title: "The Sopranos",
    seasons: 6,
    episodes: 86,
    genre: "Crime, Drama",
    thumbnail: "/shows/sopranos-thub.jpg",
    platform: "Max",
    platformSlug: "max",
    slug: "the-sopranos",
    banner: "/shows/the-sopranos-banner.jpg",
    logo: "/shows/the-sopranos-logo.svg",
    description:
      "Kriminální drama o mafiánském bossovi Tony Soprano a jeho osobních i profesních problémech. Seriál je známý svým hlubokým zpracováním postav.",
  },
  {
    title: "True Detective",
    seasons: 3,
    episodes: 24,
    genre: "Crime, Drama, Mystery",
    platform: "Max",
    platformSlug: "max",
    banner: "/shows/true-detective-banner.jpg",
    slug: "true-detective",
    logo: "/shows/true-detective-logo.png",
    thumbnail: "/shows/true-detective-thub.jpg",
    description:
      "Antologický kriminální seriál, kde každá sezóna představuje nový příběh a nové postavy. Zkoumá temné stránky lidské přirozenosti.",
  },
  {
    title: "Sherlock",
    seasons: 4,
    episodes: 13,
    genre: "Crime, Drama, Mystery",
    thumbnail: "/shows/sherlock-thub.jpg",
    platform: "Netflix",
    platformSlug: "netflix",
    banner: "/shows/sherlock-banner.jpg",
    logo: "/shows/sherlock-logo.png",
    slug: "sherlock",
    description:
      "Moderní adaptace klasických detektivních příběhů Sherlocka Holmese. Seriál sleduje geniálního detektiva a jeho věrného přítele Dr. Watsona.",
  },
  {
    title: "Dexter",
    seasons: 8,
    episodes: 96,
    genre: "Crime, Drama, Mystery",
    thumbnail: "/shows/dexter-thub.jpg",
    platform: "SkyShowtime",
    platformSlug: "skyshowtime",
    banner: "/shows/dexter-banner.jpg",
    logo: "/shows/dexter-logo.svg",
    slug: "dexter",
    description:
      "Seriál o forenzním specialistovi, který je zároveň sériovým vrahem. Dexter Morgan své oběti vybírá mezi těmi, kteří unikli spravedlnosti.",
  },
  {
    title: "House of Cards",
    seasons: 6,
    episodes: 73,
    genre: "Drama",
    thumbnail: "/shows/house-of-cards-thub.jpg",
    logo: "/shows/house-of-cards-logo.png",
    platform: "Netflix",
    platformSlug: "netflix",
    banner: "/shows/house-of-cards-banner.jpg",
    slug: "house-of-cards",
    description:
      "Politický thriller o nemilosrdném politikovi, který se nezastaví před ničím, aby získal moc. Seriál zkoumá intriky a korupci ve vysoké politice.",
  },
  {
    title: "Brooklyn Nine-Nine",
    seasons: 8,
    episodes: 153,
    genre: "Comedy, Crime",
    thumbnail: "/shows/brooklyn-thub.avif",
    logo: "/shows/brooklyn-nine-nine-logo.png",
    platform: "Peacock",
    platformSlug: "peacock",
    banner: "/shows/brooklyn-nine-nine-banner.jpg",
    slug: "brooklyn-nine-nine",
    description:
      "Komediální seriál sledující tým detektivů v 99. okrsku New Yorku. Seriál je známý svým humorem a sympatickými postavami.",
  },
  {
    title: "The Walking Dead",
    seasons: 11,
    episodes: 177,
    genre: "Drama, Horror, Thriller",
    thumbnail: "/shows/the-walking-dead-thub.jpeg",
    logo: "/shows/the-walking-dead-logo.svg",
    platform: "Netflix",
    platformSlug: "netflix",
    banner: "/shows/the-walking-dead-banner.jpg",
    slug: "the-walking-dead",
    description:
      "Post-apokalyptický seriál o přežití v světě zaplaveném zombiemi. Skupina přeživších bojuje o život a hledá bezpečné místo.",
  },
  {
    title: "Mr. Robot",
    seasons: 4,
    episodes: 45,
    genre: "Crime, Drama, Thriller",
    thumbnail: "/shows/mr-robot-thub.jpg",
    logo: "/shows/mr-robot-logo.svg",
    platform: "Amazon Prime Video",
    platformSlug: "amazon-prime-video",
    banner: "/shows/mr-robot-banner.jpg",
    slug: "mr-robot",
    description:
      "Thriller o mladém programátorovi, který se zaplete do podvratné hackerské skupiny. Seriál zkoumá témata morálky, identity a duševního zdraví.",
  },
  {
    title: "Homeland",
    seasons: 8,
    episodes: 96,
    genre: "Crime, Drama, Mystery",
    thumbnail: "/shows/homeland-thub.jpg",
    logo: "/shows/homeland-logo.png",
    platform: "Max",
    platformSlug: "max",
    banner: "/shows/homeland-banner.jpg",
    slug: "homeland",
    description:
      "Seriál sleduje agentku CIA Carrie Mathison a její boj proti terorismu. Seriál je známý svými napínavými zvraty a komplexními postavami.",
  },
  {
    title: "The Marvelous Mrs. Maisel",
    seasons: 4,
    episodes: 34,
    genre: "Comedy, Drama",
    thumbnail: "/shows/maisel-thub.webp",
    logo: "/shows/the-marvelous-mrs-maisel-logo.svg",
    platform: "Amazon Prime Video",
    platformSlug: "amazon-prime-video",
    banner: "/shows/the-marvelous-mrs-maisel-banner.jpg",
    slug: "the-marvelous-mrs-maisel",
    description:
      "Komediální drama o ženě v 50. letech, která se stane stand-up komičkou. Seriál zkoumá její cestu za slávou a osobní život.",
  },
  {
    title: "The Big Bang Theory",
    seasons: 12,
    episodes: 279,
    genre: "Comedy, Romance",
    thumbnail: "/shows/big-ban-theory-thub.jpg",
    logo: "/shows/the-big-bang-theory-logo.png",
    platform: "Max",
    platformSlug: "max",
    banner: "/shows/the-big-bang-theory-banner.jpg",
    slug: "the-big-bang-theory",
    description:
      "Komediální seriál o skupině vědců a jejich přátelích. Seriál sleduje jejich každodenní život a vtipné situace spojené s jejich zálibami.",
  },
  {
    title: "How I Met Your Mother",
    seasons: 9,
    episodes: 208,
    genre: "Comedy, Romance",
    logo: "/shows/how-i-met-your-mother-logo.png",
    thumbnail: "/shows/mother-thub.webp",
    platform: "Hulu",
    platformSlug: "hulu",
    banner: "/shows/how-i-met-your-mother-banner.jpg",
    slug: "how-i-met-your-mother",
    description:
      "Komediální seriál o muži, který vypráví svým dětem příběh o tom, jak potkal jejich matku. Seriál sleduje jeho přátelství a romantické vztahy.",
  },
  {
    title: "Lost",
    seasons: 6,
    episodes: 121,
    genre: "Adventure, Drama, Fantasy",
    logo: "/shows/lost-logo.png",
    thumbnail: "/shows/lost-thub.jpeg",
    banner: "/shows/lost-banner.jpg",
    platform: "Hulu",
    platformSlug: "hulu",
    slug: "lost",
    description:
      "Dramatický seriál o skupině lidí, kteří přežili pád letadla na tajemném ostrově. Seriál zkoumá jejich snahu o přežití a odhalení tajemství ostrova.",
  },
  {
    title: "The Simpsons",
    seasons: 34,
    episodes: 750,
    genre: "Animation, Comedy",
    logo: "/shows/the-simpsons-logo.svg",
    banner: "/shows/the-simpsons-banner.jpg",
    thumbnail: "/shows/simpsons-thub.webp",
    platform: "Disney+",
    platformSlug: "disney-plus",
    slug: "the-simpsons",
    description:
      "Dlouhotrvající animovaný seriál o rodině Simpsonových. Seriál je známý svým humorem a satirickým pohledem na americkou společnost.",
  },
];

export const streamingPlatforms = [
  {
    name: "Netflix",
    logo: "/netflix-logo.jpg",
    color: "#E50914",
    slug: "netflix",
  },
  {
    name: "Max",
    logo: "/max-logo.avif",
    color: "#5a2d82",
    slug: "max",
  },
  {
    name: "Amazon Prime Video",
    logo: "/prime-logo.jpg",
    color: "#00A8E1",
    slug: "amazon-prime-video",
  },
  {
    name: "Disney",
    logo: "/disney-logo.webp",
    color: "#113CCF",
    slug: "disney-plus",
  },
  {
    name: "Hulu",
    logo: "/hulu-logo.png",
    color: "#1CE783",
    slug: "hulu",
  },
  {
    name: "Peacock",
    logo: "/peacock-logo.jpg",
    color: "#000000",
    slug: "peacock",
  },
  {
    name: "SkyShowtime",
    logo: "/skyshowtime-logo.jpg",
    color: "#0D47A1",
    slug: "skyshowtime",
  },
];

// const seriesList = [
//   "Breaking Bad",
//   "Game of Thrones",
//   "Stranger Things",
//   "The Mandalorian",
//   "The Crown",
//   "Friends",
//   "Westworld",
//   "The Witcher",
//   "Dark",
//   "Black Mirror",
//   "Fargo",
//   "Mindhunter",
//   "The Boys",
//   "Better Call Saul",
//   "Chernobyl",
//   "The Expanse",
//   "The Handmaid's Tale",
//   "Peaky Blinders",
//   "Narcos",
//   "The Umbrella Academy",
//   "Rick and Morty",
//   "Ozark",
//   "Succession",
//   "Money Heist",
//   "The Office",
//   "Parks and Recreation",
//   "The Sopranos",
//   "True Detective",
//   "Sherlock",
//   "Dexter",
//   "House of Cards",
//   "Brooklyn Nine-Nine",
//   "The Walking Dead",
//   "Mr. Robot",
//   "Homeland",
//   "The Marvelous Mrs. Maisel",
//   "The Big Bang Theory",
//   "How I Met Your Mother",
//   "Lost",
//   "Supernatural",
//   "The Flash",
//   "Arrow",
//   "The 100",
//   "Grey's Anatomy",
//   "Gotham",
//   "The Good Place",
//   "Vikings",
//   "Lucifer",
//   "Prison Break",
//   "Community",
// ];
